import {Dimensions, StyleSheet} from 'react-native';
import React from 'react';

const sWidth = Dimensions.get('window').width;
const sHeight = Dimensions.get('window').height;
const ratio = sWidth / sHeight; //sWidth = ratio * sHeight

const styles = StyleSheet.create({
  backgroundStyle: {
    flex: 1,
    backgroundColor: 'red',
  },
  backgroundGradient: {
    flex: 1,
    width: '100%',
  },
  container: {
    flex: 1,
    width: '90%',
    margin: 20,
    backgroundColor: 'white',
    borderColor: 'transparent',
    borderWidth: 1,
    borderRadius: 30,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 3,
    overflow: 'hidden',
  },
  containerGradient: {
    // flex: 1,
    // width: '100%',
    // borderColor: 'transparent',
    // borderWidth: 1,
    // borderRadius: 30,
    // shadowColor: '#000',
    // shadowOffset: {
    //   width: 0,
    //   height: 2,
    // },
    // shadowOpacity: 0.25,
    // shadowRadius: 3.84,
    // elevation: 2,
    width: sHeight * 2,
    height: sHeight * 2,
    borderRadius: sHeight * 1,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    backgroundColor: '#aaa',
    alignItems: 'center',
    marginLeft: ratio * sHeight * 0.5 - sHeight,
    marginTop: -sHeight * 1.7,
    paddingTop: sHeight * 1.7,
  },
  headerIconsContainer: {
    // backgroundColor: 'red',
    width: '25%',
    flex: 0.03,
    borderColor: 'transparent',
    borderWidth: 0.5,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    padding: 10,
    marginTop: 15,
    marginLeft: -40,
  },
  bgLeftDotStyleOne: {
    height: 30,
    width: 30,
    backgroundColor: '#faace8',
    opacity: 0.6,
    borderColor: 'transparent',
    borderWidth: 0.5,
    borderRadius: 15,
    shadowColor: 'transparent',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 1,
    position: 'absolute',
    top: '10%',
    left: '12%',
  },
  bgLeftDotStyleTwo: {
    height: 20,
    width: 20,
    backgroundColor: '#ffa8eb',
    opacity: 0.4,
    borderColor: 'transparent',
    borderWidth: 0.5,
    borderRadius: 10,
    shadowColor: 'transparent',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 1,
    position: 'absolute',
    top: '15%',
    left: '7%',
  },
  userInfoContainer: {
    alignItems: 'center',
    marginTop: '5%',
    width: '15%',
    // backgroundColor: 'green',
    marginLeft: -20,
  },
  userNameStyle: {
    color: 'white',
    fontFamily: 'sans-serif-medium',
    fontSize: 18,
    fontWeight: 'bold',
  },
  bgRightDotStyleOne: {
    height: 15,
    width: 15,
    // backgroundColor: '#faace8',
    opacity: 0.3,
    borderColor: 'white',
    opacity: 0.2,
    borderWidth: 1,
    borderRadius: 7,
    shadowColor: 'transparent',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 1,
    position: 'absolute',
    top: '21%',
    right: '5%',
  },
  bgRightDotStyleTwo: {
    height: 25,
    width: 25,
    // backgroundColor: '#faace8',
    opacity: 0.3,
    borderColor: 'white',
    opacity: 0.2,
    borderWidth: 1,
    borderRadius: 13,
    shadowColor: 'transparent',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 1,
    position: 'absolute',
    top: '24.3%',
    right: 25,
  },


  Bottom_background: {
    width: sHeight * 2,
    height: sHeight * 2,
    borderRadius: sHeight * 1,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    backgroundColor: '#edd8ed',
    alignItems: 'center',
    marginLeft: ratio * sHeight * 0.5 - sHeight,
    marginBottom: -sHeight * 1.7,
    paddingBottom: sHeight * 1.7,
    marginTop: 40,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  Bottom_content: {
    paddingTop: sHeight * 0.06,
    width: '22%',
    height: sHeight * 0.6,
    alignItems: 'center',
    backgroundColor: '#fcedfc',
    marginLeft: '-3%',
    marginTop: '10%',
    borderColor: 'transparent',
    borderWidth: 1,
    borderBottomLeftRadius: 35,
    borderBottomRightRadius: 35,
    shadowColor: '#e87aeb',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 3.84,
    elevation: 3,
    overflow: 'hidden',
  },
  profileImgContainer: {
    height: 90,
    width: 90,
    backgroundColor: 'transparent',
    position: 'absolute',
    top: '28%',
    left: '37%',
    borderColor: 'transparent',
    borderWidth: 1,
    borderRadius: 45,
    zIndex: 1,
    shadowColor: '#e87aeb',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 3.84,
    elevation: 9,
  },
  profileImgStyle: {
    height: 89,
    width: 89,
    borderColor: 'transparent',
    borderWidth: 1,
    borderRadius: 45,
  },
  btnBelowDPStyle: {
    height: 160,
    width: 170,
    backgroundColor: '#edd8ed',
    // position: 'absolute',
    borderColor: '#e002bf',
    borderWidth: 1,
    borderRadius: 90,
    marginTop: '-30%',
    shadowColor: 'black',
    shadowOffset: {
      width: 2,
      height: 2,
    },
    shadowOpacity: 0.9,
    shadowRadius: 3.84,
    elevation: 6,
  },
  facebookIconContainer: {
    height: 35,
    width: 35,
    borderColor: '#e002bf',
    borderWidth: 1,
    borderRadius: 20,
    position: 'absolute',
    top: '60%',
    left: '10%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  internetIconContainer: {
    height: 35,
    width: 35,
    borderColor: '#e002bf',
    borderWidth: 1,
    borderRadius: 20,
    position: 'absolute',
    top: '75%',
    left: '40%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  twitterIconContainer: {
    height: 35,
    width: 35,
    borderColor: '#e002bf',
    borderWidth: 1,
    borderRadius: 20,
    position: 'absolute',
    top: '60%',
    left: '69%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  followerContainer: {
    height: 50,
    width: 90,
    // backgroundColor: 'red',
    position: 'absolute',
    top: '31%',
    left: '7%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  noOfFollowerTextStyle: {
    fontSize: 17,
    color: '#e002bf',
    fontWeight: 'bold',
  },
  followeTextStyle: {
    fontSize: 14,
    color: '#e002bf',
    fontWeight: '500',
  },
  followingContainer: {
    height: 50,
    width: 90,
    // backgroundColor: 'red',
    position: 'absolute',
    top: '31%',
    left: '68%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  noOfFollowingTextStyle: {
    fontSize: 17,
    color: '#3111d6',
    fontWeight: 'bold',
  },
  followeingTextStyle: {
    fontSize: 14,
    color: '#3111d6',
    fontWeight: '500',
  },
  leftDotStyleInBackground: {
    height: 80,
    width: 80,
    backgroundColor: '#edd8ed',
    // opacity: 0.6,
    borderColor: '#aaa',
    borderWidth: 0.5,
    borderRadius: 40,
    shadowColor: 'transparent',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 1,
    position: 'absolute',
    top: '135%',
    right: '57.8%',
  },
  BottomDotStyleInBackground: {
    height: 30,
    width: 30,
    backgroundColor: '#edd8ed',
    // opacity: 0.6,
    borderColor: '#aaa',
    borderWidth: 0.5,
    borderRadius: 15,
    shadowColor: 'transparent',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 1,
    position: 'absolute',
    top: '180%',
    right: '53%',
  },
  profileDescriptionContainer: {
    width: '100%',
    // backgroundColor: 'gray',
    marginTop: 10,
    // height: '70%',
    marginLeft: '8%',
  },
  profileSingleContantContainer: {
    flexDirection: 'row',
    width: '90%',
    height: 30,
    alignItems: 'center',
  },
  profileContantIconContainer: {
    width: '10%',
    // backgroundColor: 'red',
  },
  profileContantTextContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '88%',
    height: 30,
    // backgroundColor: 'green',
    marginLeft: 15,
  },
  profileInnerRightContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 5,
  },
  profileContantBottomHorzontalLineStyle: {
    height: 0.7,
    width: '89%',
    backgroundColor: 'gray',
    marginLeft: '15%',
  },
  profileCommonStyleContantContainer: {
    flexDirection: 'row',
    width: '90%',
    height: 30,
    alignItems: 'center',
    marginTop: 10,
  },
  profileLikeContantBottomHorzontalLineStyle: {
    height: 0.5,
    width: '89%',
    backgroundColor: 'gray',
    marginLeft: '15%',
  },
  profileContantTextStyle: {
    color: '#e002bf',
    fontWeight: '700',
    fontSize: 16,
  },
  profileContantRightDigitStyle: {
    marginRight: 5,
    color: '#e002bf',
    fontWeight: '700',
    fontSize: 15,
  },
});

export default styles;
